services:
  nginx:
    image: nginx:alpine
    container_name: my_statistics_nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
  laravel:
    image: 'cosmo98/laravel-12'
    container_name: my_statistics_app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
  mysql:
    image: beercan1989/arm-mysql:latest
    container_name: my_statistics_db
    restart: always
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE} 
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - my_statistics-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9999:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql  
volumes:
  my_statistics-db:
    driver: local